# Generated by Django 3.1.1 on 2020-09-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descr', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Potatoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descr', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, null=True)),
                ('products', models.CharField(max_length=600, null=True)),
                ('total', models.CharField(max_length=6, null=True)),
                ('deliverTo', models.CharField(max_length=60, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('statusValue', models.CharField(max_length=15, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descr', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
