# Generated by Django 3.1.1 on 2020-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolemix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantain',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='food/imgs/plantain'),
        ),
        migrations.AddField(
            model_name='potatoe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='food/imgs/potato'),
        ),
        migrations.AddField(
            model_name='yam',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='food/imgs/yam'),
        ),
    ]
